loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runs {
        data {
            inherit client

            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=reterraforged"

            runDir "build/datagen"
        }
    }
}

configurations {
    commonCompile
    commonRuntime
    compileClasspath.extendsFrom commonCompile
    runtimeClasspath.extendsFrom commonRuntime
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    implementation("net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
    runtimeOnly "curse.maven:terrablender-fabric-565956:7834072"

    commonCompile(project(path: ":common", configuration: "apiElements")) { transitive false }
    commonRuntime(project(path: ":common", configuration: "runtimeElements")) { transitive false }
}

sourceSets {
    main {
        resources {
            srcDirs += [
                "src/main/generated"
            ]
        }
    }
}

repositories {
    maven { url "https://maven.glitchfiend.com/public" }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

jar {
    archiveClassifier = "fabric-${rootProject.minecraft_version}"
    dependsOn project(":common").tasks.named("classes")
    from(project(":common").sourceSets.main.output)
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
    exclude "fabric.mod.json"
    exclude "*.mixins.json"
    exclude "*.accesswidener"
}
