plugins {
    id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT" apply false
}

subprojects {
    apply plugin: "net.fabricmc.fabric-loom"

    loom {
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"

    base.archivesName = rootProject.archives_base_name
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        maven {
            url "https://maven.shedaniel.me"
            content {
                excludeGroup "curse.maven"
            }
        }
        maven {
            url "https://maven.glitchfiend.com/public"
            content {
                excludeGroup "curse.maven"
            }
        }
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 25
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
        withSourcesJar()
    }
}
