org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
minecraft_version=26.1
archives_base_name=reterraforged
mod_version=0.1.0
mod_id=reterraforged
maven_group=raccoonman.reterraforged
fabric_loader_version=0.19.2
fabric_api_version=0.145.1+26.1
terrablender_version=26.1.0.2